# Generated by Django 3.2.23 on 2024-05-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_name',
            field=models.CharField(default='Some string', max_length=200),
        ),
    ]
