# Generated by Django 3.2.23 on 2024-05-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_movie_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_extension',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
