# Generated by Django 3.2.23 on 2024-10-15 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20241014_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 0, 48, 52, 304512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 0, 48, 52, 288837, tzinfo=utc)),
        ),
    ]
