# Generated by Django 3.2.23 on 2024-10-17 01:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20241016_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAdmin',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.comment')),
            ],
            bases=('store.comment',),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 1, 2, 19, 536146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 17, 1, 2, 19, 536146, tzinfo=utc)),
        ),
    ]
