# Generated by Django 3.2.23 on 2024-10-29 23:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20241023_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 23, 31, 9, 427766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 23, 31, 9, 427766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='store.photo'),
        ),
    ]
